### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by mguinness** [mstum/Simplexcel#15]
Due the release of [.NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-standard-2-0/) it would be a good idea for the project to target it.

.NET Standard 2.0 is supported on the following platforms:

- .NET Framework 4.6.1
- .NET Core 2.0
- Mono 5.4
- Xamarin.iOS 10.14
- Xamarin.Mac 3.8
- Xamarin.Android 7.5
- Upcoming version of UWP

**Comment by mguinness** [comment]
I'd also suggest the following tags to help people discover this library in nuget.

`<PackageTags>xlsx excel ooxml netcore netstandard</PackageTags>`

**Comment by mstum** [comment]
Will have to evaluate this - I'm not sure what .net Standard 2.0 would offer more over 1.3 (apart from DateTime.ToOADate), but if it still works with older Visual Studio (at least 2015, preferably 2012), that might be worth it. Pretty sure I can't get rid off the net45 build though because of old Visual Studio support.

**Comment by mguinness** [comment]
I guess it's of limited use right now.  I believe they [backported support](https://github.com/dotnet/cli/issues/6739) into VS 2015, but not 2012/2013.

**Comment by Jacquers** [comment]
+1 for this please, we are using .net core 2 and this library would be very useful for us :)

**Comment by mstum** [comment]
@Jacquers Just checking, wouldn't the library already work with .net Core 2? It's targeting .net Standard 1.3 (in addition to .net 4.5), and I think that .net Core 2.x should be able to use .net Standard 1.x libraries?

That said, with .net Core being the preferred version these days, I think I'm just going to retarget it to .net Standard 2.0 since that's what I'm using for all new libraries anyway.

**Comment by Jacquers** [comment]
Hi,


Yes, it is working as it is 😊


Thank you,

Jacques


________________________________

**Comment by mstum** [comment]
I've just published [Version 2.2.0.60](https://www.nuget.org/packages/simplexcel/2.2.0.60), which includes netstandard2.0 as well as netstandard13 and net45.
